ボウリングのスコア計算プログラムを作成
KMZ0209/ruby-practices pull request #3
Opened 2022-11-05 08:36 UTC by KMZ0209

2022-11-10 16:29 UTC, u1tnk commented on 04.bowling/bowling.rb
> +frames = frames[0..8] << array
このとき最後のframeは `[[6, 4], [5]]`と配列が入れ子になっています。
それを前提に処理していると思いますが、こういう直感に反するフォーマットでデータが入っているのは混乱してバグを発生させる原因によくなります。
`[6, 4, 5]`のように他のfrmaeと同じ形式にしましょう。

2022-11-10 16:37 UTC, u1tnk requested changes

2022-11-10 16:37 UTC, u1tnk commented on 04.bowling/bowling.rb
> +array = frames[9..]
変数とするときに `array`は配列であることしか情報が無いのでNGです。
ほぼ意味が無い変数名で許容されるのは ごく短かいときのブロック引数ぐらいなので必ず意味のある名前にしましょう。
ただ、今回のようにごく短いときは `frames[0..8] << frames[9..]`のように変数を作らない方が分かりやすいと思います。

2022-11-10 16:37 UTC, u1tnk commented on 04.bowling/bowling.rb
> +frame = frames.pop
ここもframeでは無く last_frameにした方が良いですね。

2022-11-10 16:37 UTC, u1tnk commented on 04.bowling/bowling.rb
> +frame.each do |last_frame|
ここは前述のデータ形式が変わればもっとシンプルに書けますね。

2022-11-10 16:37 UTC, u1tnk commented on 04.bowling/bowling.rb
> +array = frames[9..]
また、今回あまり関係無くなると思いますが、ruby界隈では配列であることを表すのに複数形を使うのが一般的です。
arrayや xxx_arrayという名前はほぼ使わないので複数形を使うように気をつけてください。

2022-11-17 16:11 UTC, KMZ0209 commented
@u1tnk さん　レビューいただきありがとうございました。アドバイスを基に修正しましたので、再度チェックをお願い致します。

2022-11-19 00:46 UTC, u1tnk approved these changes

2022-11-27 13:52 UTC, merged